apiVersion: v1
kind: Secret
metadata:
  name: notification-api-secret
  labels:
    app: notification-api
stringData:
  SMTP__PASSWORD: "ognvktjcexjeiowl"
  RABBITMQ__PASSWORD: "admin123"
  JWT__ISSUER: "FCG-Notifications"
  JWT__KEY: "ChaveSuperSecretaComMaisDe32CaracteresAqui12345"