apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-api-config
  labels:
    app: notification-api
data:
  RABBITMQ__URL: "rabbitmq"
  RABBITMQ__USERNAME: "admin"
  SMTP__SERVER: "smtp.gmail.com"
  SMTP__PORT: "587"
  SMTP__USER: "fiapclound@gmail.com"
  LOGGING__LOGLEVEL__DEFAULT: "Information"
  LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: "Warning"
  ALLOWEDHOSTS: "*"
