apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-api-config
  labels:
    app: notification-api
data:
  rabbitHost: "rabbitmq"

  # colocar nome das filas aqui quando tiver mais detalhes
