apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api-deployment
  labels:
    app: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
        - name: notification-api
          image: notification-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: Rabbitmq__Url
              valueFrom:
                configMapKeyRef:
                  name: notification-api-config
                  key: RABBITMQ__URL
            - name: Rabbitmq__Username
              valueFrom:
                configMapKeyRef:
                  name: notification-api-config
                  key: RABBITMQ__USERNAME
            - name: Rabbitmq__Password
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: RABBITMQ__PASSWORD
            - name: Smtp__Server
              valueFrom:
                configMapKeyRef:
                  name: notification-api-config
                  key: SMTP__SERVER
            - name: Smtp__Port
              valueFrom:
                configMapKeyRef:
                  name: notification-api-config
                  key: SMTP__PORT
            - name: Smtp__User
              valueFrom:
                configMapKeyRef:
                  name: notification-api-config
                  key: SMTP__USER
            - name: Smtp__Password
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: SMTP__PASSWORD
