apiVersion: v1
kind: Service
metadata:
  name: users-sqlserver
  labels:
    app: users-sqlserver
spec:
  type: ClusterIP
  selector:
    app: users-sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
