apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api-deployment
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: payments-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__ConnectionStrings
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: CONNECTIONSTRINGS__CONNECTIONSTRINGS
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: JWT__ISSUER
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: JWT__KEY
            - name: Rabbitmq__Url
              valueFrom:
                configMapKeyRef:
                  name: payments-api-config
                  key: RABBITMQ__URL
            - name: Rabbitmq__Username
              valueFrom:
                configMapKeyRef:
                  name: payments-api-config
                  key: RABBITMQ__USERNAME
            - name: Rabbitmq__Password
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: RABBITMQ__PASSWORD