apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  labels:
    app: payments-api
stringData:
  connectionString: "Server=payments-sqlserver;Database=FCGPayments;User Id=sa;Password=pass@123;TrustServerCertificate=True"
  jwtIssuer: "fcg-payments"
  jwtKey: "super_secret_dev_key_change_me"
