apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api-deployment
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: payments-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: connectionString
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: jwtIssuer
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: payments-api-secret
                  key: jwtKey
            - name: Rabbit__Host
              valueFrom:
                configMapKeyRef:
                  name: payments-api-config
                  key: rabbitHost
