apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  labels:
    app: catalog-api
data:
  RABBITMQ__URL: "rabbitmq"
  RABBITMQ__USERNAME: "admin"
  API__USER: "http://users-api:8080/"
  LOGGING__LOGLEVEL__DEFAULT: "Information"
  LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: "Warning"
  ALLOWEDHOSTS: "*"
