apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: catalog-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__ConnectionStrings
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secret
                  key: CONNECTIONSTRINGS__CONNECTIONSTRINGS
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secret
                  key: JWT__ISSUER
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secret
                  key: JWT__KEY
            - name: Rabbitmq__Url
              valueFrom:
                configMapKeyRef:
                  name: catalog-api-config
                  key: RABBITMQ__URL
            - name: Rabbitmq__Username
              valueFrom:
                configMapKeyRef:
                  name: catalog-api-config
                  key: RABBITMQ__USERNAME
            - name: Rabbitmq__Password
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secret
                  key: RABBITMQ__PASSWORD
            - name: Api__User
              valueFrom:
                configMapKeyRef:
                  name: catalog-api-config
                  key: API__USER