apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
stringData:
  connectionString: "Server=sqlserver;Database=FCGCatalog;User Id=sa;Password=pass@123;TrustServerCertificate=True"
  jwtIssuer: "fcg-calog"
  jwtKey: "super_secret_dev_key_change_me"
