apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
stringData:
  CONNECTIONSTRINGS__CONNECTIONSTRINGS: "Server=catalog-sqlserver,1433;Initial Catalog=db_fcg_catalog;Persist Security Info=False;User ID=sa;Password=pass@123;Encrypt=False;Pooling=True;TrustServerCertificate=True"
  JWT__ISSUER: "FCG-Users"
  JWT__KEY: "ChaveSuperSecretaComMaisDe32CaracteresAqui12345"
  RABBITMQ__PASSWORD: "admin123"
