apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
type: Opaque
stringData:
  rabbitmq-username: "admin"
  rabbitmq-password: "admin123"
  rabbitmq-erlang-cookie: "secretcookie123456"
