apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  labels:
    app: users-api
stringData:
  CONNECTIONSTRINGS__CONNECTIONSTRINGS: "Server=users-sqlserver,1433;Initial Catalog=db_fcg_users;Persist Security Info=False;User ID=sa;Password=pass@123;Encrypt=False;Pooling=True;TrustServerCertificate=True"
  JWT__ISSUER: "FCG-Users"
  JWT__KEY: "ChaveSuperSecretaComMaisDe32CaracteresAqui12345"
  RABBITMQ__PASSWORD: "admin123"
