apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  labels:
    app: users-api
data:
  RABBITMQ__URL: "rabbitmq"
  RABBITMQ__USERNAME: "admin"
  LOGGING__LOGLEVEL__DEFAULT: "Information"
  LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: "Warning"
  ALLOWEDHOSTS: "*"
